project_name: cashu-feni

builds:
  - id: mint-server
    binary: cashu-feni-mint
    main: ./cmd/mint/mint.go
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - 7
      - 6
      - 5
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: openbsd
        goarch: amd64
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
  - id: feni-client
    binary: cashu-feni-client
    main: ./cmd/cashu/feni.go
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - 7
      - 6
      - 5
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: amd64
      - goos: openbsd
        goarch: arm64
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
